server:
  port: 8082

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: plan-service
          uri: lb://plan-service
          predicates:
            - Path=/plans/**
        - id: usage-service
          uri: lb://usage-service
          predicates:
            - Path=/usage-logs/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
